#!/usr/bin/env python3
"""Generate the ASCII portrait used on the site from misc/pfp.png.

Emits src/ascii.ts with a single rendering that maps dark pixels to dense
glyphs, i.e. black ink on white paper. The same art is used in both themes:
inverting the ramp for the dark theme was tried and looks worse, because
this sitter's hair is the darkest thing in frame, so an inverted ramp blanks
it out and the head loses its silhouette entirely. Keeping the ink ramp
turns the dark theme into a woodcut -- tonally a negative, but the shape
stays unmistakable, which matters more.

The studio backdrop is dropped by a plain luminance threshold: it runs
202..226 across the whole frame while every part of the sitter's skin and
hair sits at or below 193, so the two never overlap. The white t-shirt
(227+) falls out with the backdrop, which is fine -- the frame is cropped
to the head anyway.

Usage: python3 scripts/gen-ascii.py [--cols N] [--threshold N]
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
from PIL import Image, ImageEnhance, ImageFilter
from scipy import ndimage

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "misc" / "pfp.png"
OUT = ROOT / "src" / "ascii.ts"

# Sparse -> dense. Chosen for even perceived-weight steps in a mono font.
RAMP = " .:-=+*#%@"

# Terminal cells are about twice as tall as they are wide.
CELL_ASPECT = 0.5

# Anything at or above this luminance is backdrop, not sitter.
SUBJECT_MAX_LUMA = 197

# Keep the head and jaw, drop the neck and t-shirt below it.
HEAD_CROP = 0.70


def subject_mask(gray: Image.Image, threshold: int) -> Image.Image:
    """Binary mask of the sitter's head, cleaned of backdrop artefacts."""
    m = np.asarray(gray) < threshold

    # Curly flyaway strands read as specks floating in the backdrop; keeping
    # only the largest blob drops them without touching the head itself.
    labels, count = ndimage.label(m)
    if count > 1:
        sizes = ndimage.sum(m, labels, range(1, count + 1))
        m = labels == (int(np.argmax(sizes)) + 1)

    m = ndimage.binary_fill_holes(m)
    # Erode the fuzzy hair/backdrop rim, which is mid-grey and would other-
    # wise glow as a bright halo in the inverted rendering.
    m = ndimage.binary_erosion(m, iterations=4)

    return Image.fromarray((m * 255).astype(np.uint8), mode="L")


def render(gray: Image.Image, mask: Image.Image, cols: int) -> str:
    w, h = gray.size
    rows = max(1, round(cols * (h / w) * CELL_ASPECT))

    small = gray.resize((cols, rows), Image.Resampling.LANCZOS)
    small = ImageEnhance.Contrast(small).enhance(1.3)
    # Bilinear keeps partial coverage at the silhouette edge, so the >128
    # test below behaves like a half-pixel cutoff instead of aliasing.
    small_mask = mask.resize((cols, rows), Image.Resampling.BILINEAR)

    px = np.asarray(small, dtype=float)
    inside = np.asarray(small_mask) > 128

    # Normalise the sitter's own range so the ramp gets used end to end.
    subject = px[inside]
    lo, hi = (subject.min(), subject.max()) if subject.size else (0.0, 255.0)
    v = np.clip((px - lo) / max(1.0, hi - lo), 0.0, 1.0)
    v = v * v * (3 - 2 * v)  # smoothstep: opens up the compressed mid-tones
    v = 1.0 - v  # dark pixel -> dense glyph

    idx = np.rint(v * (len(RAMP) - 1)).astype(int)
    lines = [
        "".join(RAMP[idx[y, x]] if inside[y, x] else " " for x in range(cols)).rstrip()
        for y in range(rows)
    ]

    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    indent = min((len(l) - len(l.lstrip()) for l in lines if l.strip()), default=0)
    return "\n".join(l[indent:] for l in lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cols", type=int, default=54)
    # neofetch prints its logo beside the info block, so that copy has to be
    # narrow enough that both fit the 76-column window.
    ap.add_argument("--small-cols", type=int, default=34)
    ap.add_argument("--threshold", type=int, default=SUBJECT_MAX_LUMA)
    args = ap.parse_args()

    gray = Image.open(SRC).convert("L")
    # Soften skin and hair grain so the ramp tracks form, not sensor noise.
    gray = gray.filter(ImageFilter.MedianFilter(size=5))
    gray = gray.crop((0, 0, gray.width, int(gray.height * HEAD_CROP)))

    mask = subject_mask(gray, args.threshold)
    box = mask.getbbox()
    if box:
        gray, mask = gray.crop(box), mask.crop(box)

    art = render(gray, mask, args.cols)
    small = render(gray, mask, args.small_cols)

    OUT.write_text(
        "// Generated by scripts/gen-ascii.py from misc/pfp.png -- do not edit.\n"
        "// Regenerate after replacing the photo: python3 scripts/gen-ascii.py\n\n"
        f"export const PORTRAIT = String.raw`\n{art}\n`.slice(1, -1);\n\n"
        f"export const PORTRAIT_SMALL = String.raw`\n{small}\n`.slice(1, -1);\n"
    )

    print(f"wrote {OUT.relative_to(ROOT)}")
    for label, a in (("portrait", art), ("small", small)):
        rows = a.splitlines()
        print(f"\n--- {label}: {max(len(r) for r in rows)} cols x {len(rows)} rows ---")
        print(a)


if __name__ == "__main__":
    main()
